name: Docker

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Release Version
        id: version
        run: |
          echo "::set-output name=release::$( \
            curl -sL https://api.github.com/repos/pilina/cloudflared/releases/latest \
            | jq -r '.tag_name')"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pilina/cloudflared:${{ steps.version.outputs.release }}
          build-args: VERSION=${{ steps.version.outputs.release }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
